### ISSUE TITLE
Release 0.9.6 contains forced debug loglevel

### ISSUE THREAD

**Issue by Shuro** [pschmitt/pyrundeck#21]
Hi there,
you had an pull request for issue  #17, which got merged. But due to the fact that there is no new release, the version which is installed via pip3 is still using the old faulty code.

Please make a new minor release. :sweat_smile: 

Best regards
Shuro

**Comment by pschmitt** [comment]
Done: https://pypi.org/project/pyrundeck/0.9.7/
