### ISSUE TITLE
Support for file uploads

### ISSUE THREAD

**Issue by BraxtonLowers** [pschmitt/pyrundeck#39]
Is this project open to a pull request for wrapping the file upload API of rundeck? The rundeck implementation can be found [here](https://docs.rundeck.com/docs/api/rundeck-api.html#upload-a-file-for-a-job-option). It looks like we'd just need to add a parameter to __post and __request to change the Content-type to octet/stream and add a data payload to the options kwarg.

**Comment by pschmitt** [comment]
Hi, yes sure! Send it in!

**Comment by BraxtonLowers** [comment]
Sounds good! Its almost done. I'll create a the PR once I finish testing it.

**Comment by pschmitt** [comment]
Closed by #41 

And this is now included in 0.9.11
