### ISSUE TITLE
Methods for gathering Job Definition

### ISSUE THREAD

**Issue by msilva14** [pschmitt/pyrundeck#45]
Hello.
   I'm using the module in order to read the configured jobs in Rundeck, but there is a need to get the job's definition in order to validate some dynamic calls against the configured parameters.

   So, I'd like to know how I could do to share with you the methods I created ( I cloned the Repository and I added get_job_def returning xml/yaml and get_job_meta returning xml ), to be able to use them and if possible to share those small developments too.

   Thanks in advance for your answer.

best regards

**Comment by pschmitt** [comment]
Hi, thanks for your interest in sharing code.

Ideally, you'd open a merge request for this, this way I can review and merge your stuff.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

This can also all be done via the CLI using https://github.com/cli/cli

```shell
gh pr create
```

**Comment by emersonyh** [comment]
Was implemented with the PR https://github.com/pschmitt/pyrundeck/pull/46
